/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.logging.persist.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.logging.persist.model.LoggingConfig;
import com.liferay.logging.persist.model.LoggingConfigModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LoggingConfig service. Represents a row in the &quot;LOGCFG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LoggingConfigModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoggingConfigImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoggingConfigImpl
 * @generated
 */
public class LoggingConfigModelImpl
	extends BaseModelImpl<LoggingConfig> implements LoggingConfigModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a logging config model instance should use the <code>LoggingConfig</code> interface instead.
	 */
	public static final String TABLE_NAME = "LOGCFG";

	public static final Object[][] TABLE_COLUMNS = {
		{"logConfigId", Types.BIGINT}, {"logger", Types.VARCHAR},
		{"level", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("logConfigId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("logger", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("level", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LOGCFG (logConfigId LONG not null primary key,logger VARCHAR(400) null,level VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LOGCFG";

	public static final String ORDER_BY_JPQL =
		" ORDER BY loggingConfig.logConfigId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LOGCFG.logConfigId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOGGER_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOGCONFIGID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LoggingConfigModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logConfigId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogConfigId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logConfigId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoggingConfig.class;
	}

	@Override
	public String getModelClassName() {
		return LoggingConfig.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LoggingConfig, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LoggingConfig, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoggingConfig, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LoggingConfig)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LoggingConfig, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LoggingConfig, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LoggingConfig)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LoggingConfig, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LoggingConfig, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LoggingConfig>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LoggingConfig.class.getClassLoader(), LoggingConfig.class,
			ModelWrapper.class);

		try {
			Constructor<LoggingConfig> constructor =
				(Constructor<LoggingConfig>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LoggingConfig, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LoggingConfig, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LoggingConfig, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LoggingConfig, Object>>();
		Map<String, BiConsumer<LoggingConfig, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LoggingConfig, ?>>();

		attributeGetterFunctions.put(
			"logConfigId", LoggingConfig::getLogConfigId);
		attributeSetterBiConsumers.put(
			"logConfigId",
			(BiConsumer<LoggingConfig, Long>)LoggingConfig::setLogConfigId);
		attributeGetterFunctions.put("logger", LoggingConfig::getLogger);
		attributeSetterBiConsumers.put(
			"logger",
			(BiConsumer<LoggingConfig, String>)LoggingConfig::setLogger);
		attributeGetterFunctions.put("level", LoggingConfig::getLevel);
		attributeSetterBiConsumers.put(
			"level",
			(BiConsumer<LoggingConfig, String>)LoggingConfig::setLevel);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLogConfigId() {
		return _logConfigId;
	}

	@Override
	public void setLogConfigId(long logConfigId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logConfigId = logConfigId;
	}

	@Override
	public String getLogger() {
		if (_logger == null) {
			return "";
		}
		else {
			return _logger;
		}
	}

	@Override
	public void setLogger(String logger) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logger = logger;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLogger() {
		return getColumnOriginalValue("logger");
	}

	@Override
	public String getLevel() {
		if (_level == null) {
			return "";
		}
		else {
			return _level;
		}
	}

	@Override
	public void setLevel(String level) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_level = level;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LoggingConfig.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoggingConfig toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LoggingConfig>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoggingConfigImpl loggingConfigImpl = new LoggingConfigImpl();

		loggingConfigImpl.setLogConfigId(getLogConfigId());
		loggingConfigImpl.setLogger(getLogger());
		loggingConfigImpl.setLevel(getLevel());

		loggingConfigImpl.resetOriginalValues();

		return loggingConfigImpl;
	}

	@Override
	public int compareTo(LoggingConfig loggingConfig) {
		int value = 0;

		if (getLogConfigId() < loggingConfig.getLogConfigId()) {
			value = -1;
		}
		else if (getLogConfigId() > loggingConfig.getLogConfigId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LoggingConfig)) {
			return false;
		}

		LoggingConfig loggingConfig = (LoggingConfig)object;

		long primaryKey = loggingConfig.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LoggingConfig> toCacheModel() {
		LoggingConfigCacheModel loggingConfigCacheModel =
			new LoggingConfigCacheModel();

		loggingConfigCacheModel.logConfigId = getLogConfigId();

		loggingConfigCacheModel.logger = getLogger();

		String logger = loggingConfigCacheModel.logger;

		if ((logger != null) && (logger.length() == 0)) {
			loggingConfigCacheModel.logger = null;
		}

		loggingConfigCacheModel.level = getLevel();

		String level = loggingConfigCacheModel.level;

		if ((level != null) && (level.length() == 0)) {
			loggingConfigCacheModel.level = null;
		}

		return loggingConfigCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LoggingConfig, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LoggingConfig, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoggingConfig, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LoggingConfig)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LoggingConfig, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LoggingConfig, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoggingConfig, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LoggingConfig)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LoggingConfig>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _logConfigId;
	private String _logger;
	private String _level;

	public <T> T getColumnValue(String columnName) {
		Function<LoggingConfig, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LoggingConfig)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("logConfigId", _logConfigId);
		_columnOriginalValues.put("logger", _logger);
		_columnOriginalValues.put("level", _level);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("logConfigId", 1L);

		columnBitmasks.put("logger", 2L);

		columnBitmasks.put("level", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LoggingConfig _escapedModel;

}