/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.logging.persist.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LoggingConfig service. Represents a row in the &quot;LOGCFG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.logging.persist.model.impl.LoggingConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.logging.persist.model.impl.LoggingConfigImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoggingConfig
 * @see com.liferay.logging.persist.model.impl.LoggingConfigImpl
 * @see com.liferay.logging.persist.model.impl.LoggingConfigModelImpl
 * @generated
 */
@ProviderType
public interface LoggingConfigModel extends BaseModel<LoggingConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a logging config model instance should use the {@link LoggingConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this logging config.
	 *
	 * @return the primary key of this logging config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this logging config.
	 *
	 * @param primaryKey the primary key of this logging config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log config ID of this logging config.
	 *
	 * @return the log config ID of this logging config
	 */
	public long getLogConfigId();

	/**
	 * Sets the log config ID of this logging config.
	 *
	 * @param logConfigId the log config ID of this logging config
	 */
	public void setLogConfigId(long logConfigId);

	/**
	 * Returns the logger of this logging config.
	 *
	 * @return the logger of this logging config
	 */
	@AutoEscape
	public String getLogger();

	/**
	 * Sets the logger of this logging config.
	 *
	 * @param logger the logger of this logging config
	 */
	public void setLogger(String logger);

	/**
	 * Returns the level of this logging config.
	 *
	 * @return the level of this logging config
	 */
	@AutoEscape
	public String getLevel();

	/**
	 * Sets the level of this logging config.
	 *
	 * @param level the level of this logging config
	 */
	public void setLevel(String level);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoggingConfig loggingConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoggingConfig> toCacheModel();

	@Override
	public LoggingConfig toEscapedModel();

	@Override
	public LoggingConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}